# Site settings
title: Hoang Nguyen-Tien
description: Personal website
asset_version: "8"

show_downloads: false
logo: /assets/images/profile.jpg

# This repository is the account's root GitHub Pages site.
url: "https://hoangleo963.github.io"
baseurl: ""
domain: hoangleo963.github.io

github_username: hoangleo963

# Build settings
theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

exclude:
  - .DS_Store
  - vendor/
